// AUTOGENERATED - DO NOT MODIFY
import App from '../src/views/App';

export * from '@stripe/ui-extension-sdk/version';
export const BUILD_TIME = '2026-03-19 10:59:18.9588951 -0300 -03 m=+5.754409601';

export { 
  App
 };

export default {
  "$schema": "https://stripe.com/stripe-app.schema.json",
  "distribution_type": "PRIVATE",
  "id": "com.saldacloud.manager",
  "name": "SaldaCloud Manager",
  "ui_extension": {
    "content_security_policy": {
      "connect-src": [
        "https://saldaclaw-viz.vercel.app/api"
      ],
      "purpose": ""
    },
    "views": [
      {
        "component": "App",
        "viewport": "stripe.dashboard.drawer.default"
      }
    ]
  },
  "version": "1.1.10"
};
